-- Milestone 4: transactional timer functions, server-time helper, recorded-time
-- aggregates, and Realtime setup for cross-device sessions.

-- ---------------------------------------------------------------------------
-- Server time for clock-skew reconciliation
-- ---------------------------------------------------------------------------

create or replace function public.server_now()
returns timestamptz
language sql
stable
security invoker
set search_path = ''
as $$
  select now();
$$;

revoke execute on function public.server_now() from anon;
grant execute on function public.server_now() to authenticated;

-- ---------------------------------------------------------------------------
-- start_session: one active session per user, retry-safe by client-generated id
-- ---------------------------------------------------------------------------

create or replace function public.start_session(
  p_id uuid,
  p_topic_id text,
  p_task_id uuid default null
)
returns setof public.sessions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_session public.sessions;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  -- Serialize concurrent starts for this user across devices and tabs.
  perform pg_advisory_xact_lock(hashtextextended(v_user::text, 421));

  -- Retried requests reuse the same id and simply receive the existing row.
  select * into v_session
  from public.sessions
  where id = p_id and user_id = v_user;
  if found then
    return next v_session;
    return;
  end if;

  if p_task_id is not null then
    perform 1
    from public.tasks
    where id = p_task_id
      and user_id = v_user
      and topic_id = p_topic_id
      and archived_at is null;
    if not found then
      raise exception 'Task does not exist, is archived, or belongs to another topic.';
    end if;
  end if;

  perform 1 from public.sessions
  where user_id = v_user and ended_at is null;
  if found then
    raise exception 'Another study session is already running.';
  end if;

  insert into public.sessions (id, user_id, topic_id, task_id, started_at)
  values (p_id, v_user, p_topic_id, p_task_id, now())
  returning * into v_session;

  return next v_session;
end;
$$;

revoke execute on function public.start_session(uuid, text, uuid) from anon;
grant execute on function public.start_session(uuid, text, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- stop_session: idempotent stop of the caller's session
-- ---------------------------------------------------------------------------

create or replace function public.stop_session(p_id uuid)
returns setof public.sessions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_session public.sessions;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  update public.sessions
  set ended_at = now()
  where id = p_id and user_id = v_user and ended_at is null
  returning * into v_session;

  if not found then
    -- Already stopped (retry or second tab) — return the recorded row.
    select * into v_session
    from public.sessions
    where id = p_id and user_id = v_user;
    if not found then
      raise exception 'Study session not found.';
    end if;
  end if;

  return next v_session;
end;
$$;

revoke execute on function public.stop_session(uuid) from anon;
grant execute on function public.stop_session(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- switch_session: atomically end the active session and start a new one at the
-- same server timestamp. Retry-safe because the new id is regenerated by the
-- caller only once per flow.
-- ---------------------------------------------------------------------------

create or replace function public.switch_session(
  p_id uuid,
  p_topic_id text,
  p_task_id uuid default null
)
returns table(active_session public.sessions, previous_session public.sessions)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_now timestamptz := now();
  v_current public.sessions;
  v_next public.sessions;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user::text, 421));

  select * into v_next
  from public.sessions
  where id = p_id and user_id = v_user;
  if found then
    -- Retried switch after a network failure: the new session already exists.
    active_session := v_next;
    previous_session := null;
    return next;
    return;
  end if;

  if p_task_id is not null then
    perform 1
    from public.tasks
    where id = p_task_id
      and user_id = v_user
      and topic_id = p_topic_id
      and archived_at is null;
    if not found then
      raise exception 'Task does not exist, is archived, or belongs to another topic.';
    end if;
  end if;

  select * into v_current
  from public.sessions
  where user_id = v_user and ended_at is null
  for update;

  if found then
    update public.sessions
    set ended_at = v_now
    where id = v_current.id and ended_at is null
    returning * into v_current;
  end if;

  insert into public.sessions (id, user_id, topic_id, task_id, started_at)
  values (p_id, v_user, p_topic_id, p_task_id, v_now)
  returning * into v_next;

  active_session := v_next;
  previous_session := v_current;
  return next;
end;
$$;

revoke execute on function public.switch_session(uuid, text, uuid) from anon;
grant execute on function public.switch_session(uuid, text, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Recorded-time aggregates (completed sessions only, counted exactly once)
-- ---------------------------------------------------------------------------

create or replace function public.topic_time_total(p_topic_id text)
returns bigint
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    sum(extract(epoch from (ended_at - started_at))::bigint),
    0
  )
  from public.sessions
  where user_id = auth.uid()
    and topic_id = p_topic_id
    and ended_at is not null;
$$;

revoke execute on function public.topic_time_total(text) from anon;
grant execute on function public.topic_time_total(text) to authenticated;

create or replace function public.topic_time_totals()
returns table(topic_id text, total_seconds bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select topic_id,
    sum(extract(epoch from (ended_at - started_at))::bigint) as total_seconds
  from public.sessions
  where user_id = auth.uid()
    and ended_at is not null
  group by topic_id;
$$;

revoke execute on function public.topic_time_totals() from anon;
grant execute on function public.topic_time_totals() to authenticated;

create or replace function public.task_time_totals(p_topic_id text)
returns table(task_id uuid, total_seconds bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select task_id,
    sum(extract(epoch from (ended_at - started_at))::bigint) as total_seconds
  from public.sessions
  where user_id = auth.uid()
    and topic_id = p_topic_id
    and task_id is not null
    and ended_at is not null
  group by task_id;
$$;

revoke execute on function public.task_time_totals(text) from anon;
grant execute on function public.task_time_totals(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Realtime for cross-device session updates
-- ---------------------------------------------------------------------------

alter table public.sessions replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sessions'
  ) then
    alter publication supabase_realtime add table public.sessions;
  end if;
end $$;
